[package]
name = "journey-os"
version = "0.1.0"
authors = ["Pascal Mouret <pascal.mouret@me.com>"]
edition = "2018"

[dependencies]
spin = "0.9.2"
macros = { path = "../macros" }

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]
