[build]
target = "x86_64-journey_os.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[target.x86_64-journey_os]
rustflags = ["-C", "link-arg=-Tlinker.ld"]
runner = "./runner.sh"
